import './globals.css'

import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Navbar } from './components/navbar'
import { ThemeProvider } from './components/theme-provider'
import prisma from './lib/prisma'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData({ userId }: { userId: string }) {
  const data = prisma.user.findUnique({
    where: {
      id: userId,
    },
    select: {
      colorScheme: true,
    },
  })

  return data
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { getUser } = getKindeServerSession()

  const user = await getUser()

  let data
  if (user) {
    data = await getData({ userId: user?.id as string })
  }

  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} ${data?.colorScheme ?? 'theme-orange'}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
